server:
  port: 5050
  servlet:
    context-path: /archunitspringboot
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
springdoc:
  api-docs:
    path: /api-docs

